#!/bin/bash
# vim: tabstop=4 fileformat=unix fileencoding=utf-8 filetype=sh

# license: Apache v2.0

__SCRIPT_NAME="`basename "$0"`"

if [[ "" == "${XMINGW}" ]]
then
	echo "XMINGW 環境のそとで実行しています。. env.sh した環境から実行してください。"
	exit 1
fi

case "${__SCRIPT_NAME}" in
g-ir-scanner)
	echo "cross-gir(${__SCRIPT_NAME}): INFO: Mingw-w64 のために置き換えられたコマンドを実行しています。" >> /dev/stderr
	# ln -s -f /usr/lib/gobject-introspection/giscanner/_giscanner.cpython-*-linux-gnu.so "$($XMINGW/cross pkg-config gobject-introspection-1.0 --variable libdir)/gobject-introspection/giscanner/."
	if [[ "" == "${CROSS_GIR_LIBDIR}" ]]
	then
		CROSS_GIR_LIBDIR="$($XMINGW/cross pkg-config gobject-introspection-1.0 --variable libdir)/gobject-introspection"
	else
		echo "cross-gir(${__SCRIPT_NAME}): INFO: CROSS_GIR_LIBDIR 環境変数の値を PYTHONPATH 環境変数の先頭へ追加します。${CROSS_GIR_LIBDIR}" >> /dev/stderr
	fi
	PYTHONPATH="${CROSS_GIR_LIBDIR}:${PYTHONPATH}"
	if [[ "" == "${CROSS_GIR_BINDIR}" ]]
	then
		CROSS_GIR_BINDIR="$($XMINGW/cross pkg-config gobject-introspection-1.0 --variable bindir)"
	else
		echo "cross-gir(${__SCRIPT_NAME}): INFO: CROSS_GIR_BINDIR 環境変数に設定されたパスの g-ir-scanner を実行します。${CROSS_GIR_BINDIR}" >> /dev/stderr
	fi
	${CROSS_GIR_BINDIR}/g-ir-scanner --use-binary-wrapper="$XMINGW/scripts/cross-wine" --use-ldd-wrapper=ldd --cflags-begin $(${XMINGW}/cross --cflags) --cflags-end "$@"
	exit_code="$?"
	echo "cross-gir(${__SCRIPT_NAME}): INFO: 処理を終えました。このメッセージはタイミング バグを検知するために表示しています。" >> /dev/stderr
	exit ${exit_code}
	;;
gtkdoc-scangobj)
	echo "cross-gir(${__SCRIPT_NAME}): INFO: Mingw-w64 のために置き換えられたコマンドを実行しています。" >> /dev/stderr
	GTK_DOC_KEEP_INTERMEDIATE=1 \
	/usr/bin/gtkdoc-scangobj "$@" --run=$XMINGW/scripts/cross-wine
	;;
*)
	echo "cross-gir: FAIL: $0 command is not supprted." >> /dev/stderr
	exit 1
	;;
esac

