#!/bin/bash
# vim: tabstop=4 fileformat=unix fileencoding=utf-8 filetype=sh

# license: Apatche v2.0

#PREFIX=/usr/xmingw/xmingw32
PREFIX=`dirname "$0"`
if [ "" = "${XMINGW}" ]
then
  echo "WARRNING: XMINGW 環境のそとで実行しています。 env.sh の既定の環境で実行します。"
  . "${PREFIX}/scripts/env.sh" ""
fi
PREFIX="${XMINGW}"
. "${PREFIX}/scripts/cross.env"
. "${PREFIX}/scripts/cross.opt"
. "${PREFIX}/scripts/cross.exp"

export IN_CROSS_SCRIPT="#"

if [ 0 -eq $# ]
then
  echo ${RESULT}
  exit 0;
fi

prog="$1"
shift
${prog} "$@"


